export const msg = {
    email: '올바른 이메일 형식이 아닙니다.',
    nickName: '닉네임을 입력해주세요',
    emailSuccess: '이메일 인증이 완료되었습니다.',
    emailFailed: '이메일 인증이 실패하였습니다.',
    emailDuplicate: '중복된 이메일이 있습니다.',
    nickNameDuplicate: '중복된 닉네임이 있습니다.',
    nickNameSuccess: '사용 가능한 닉네임입니다.',
    over: '카테고리는 10개 이상 선택할 수 없습니다.',
    under: '카테고리는 1개 이상 무조건 선택해야합니다.',
    nickNameUpdateSuccess: '닉네임과 이메일이 변경되었습니다.',
    nickNameEmailUpdateFalied: '이미 사용중인 이메일이거나 닉네임입니다.',
    validationNickname: '닉네임은 알파벳, 숫자, 한글만 포함할 수 있습니다.',
    timeFalied: '유효시간이 지났어요',
    nickNameVerificationPassed: '닉네임 인증을 완료해야 이메일 인증 할 수 있어요',
};
