export default function Aside() {
    return (
        <div className="flex flex-col">
            <div>
                <p>12333333333333333</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>123</p>
            </div>
            <div>
                <p>45</p>
            </div>
            <div>
                <p>45</p>
            </div>
            <div>
                <p>45</p>
            </div>
            <div>
                <p>45</p>
            </div>
            <div>
                <p>45</p>
            </div>
            <div>
                <p>45</p>
            </div>
        </div>
    );
}
